rocket_chat:
  url:
  user_name:
  password:

chat_bot:
  display_name: Doge Bot
  avatar_url: https://i.imgur.com/ZNsQPPS.jpg
  target_channels:
    - "jason_playground"
  alternative_rules:
    "bad doge": "sorry"
  pattern_matching:
    "@jason.doge": "Wow, so scare, what r you doing"

google_search:
  url: https://www.googleapis.com/customsearch/v1/siterestrict
  cx:
  api_key:

watch_dog:
  time_interval_sec: 600
  time_limit_sec: 86400
